# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/lucas/.zshrc'

autoload -Uz compinit
compinit

#function for quick git commit
function gq () {
	git add .
	git commit -m $1
	git push origin master
}

#function for quick git clone from my repository
function gc () {
	git clone https://github.com/LucasFaletra/$1
}

#function for a shortcut for cloning given repo
gc_general () {
	git clone https://github.com/$1
}


#function for updating package list and foreign package list
function pkgs () {
	pacman -Qeq > ~/ARCH/packages/package_list.txt
	pacman -Qmq > ~/ARCH/packages/AUR_packages.txt
}

#function for showing all packages and their corresponfing sizes
function pshow() {
	pacman -Qi | awk 'BEGIN{sort="sort -k2 -n"} /Name/ {name=$3} /Size/ {size=$4/1024;print name":",size,"Mb"|sort}'
}

#function for copying files to ARCH git repo
function ARCH_repo () {
	cp ~/background.jpg ~/ARCH/display/background.jpg
	cp ~/.config/i3/config ~/ARCH/display/i3_config
	cp ~/.xinitrc ~/ARCH/display/xinitrc
	pkgs
	cp ~/.config/polybar/launch.sh ~/ARCH/polybar/install.sh
	cp ~/.config/polybar/config ~/ARCH/polybar/polybar_config
	cp ~/.zshrc ~/ARCH/zsh/zshrc
}


#start spotifyd in background with spt
alias spot='spotifyd && spt'

#I'm too lazy to type the whole thing
alias shut='shutdown now'

#clean up the cache
alias pc='sudo paccache --remove'

#shortcut for installing package
alias pi='sudo pacman -S'

#shortcut for removing package
alias pr='sudo pacman -R'

#shortcut for update
alias pu='yes | sudo pacman -Syu'


#add color to basic linux commands
alias ls='ls --color=auto'
alias diff='diff --color=auto'
alias grep='grep --color=auto'


alias vim='sudo nvim'

#prompt for user
PS1='%F{cyan}%n%f@%F{blue}%m%f %F{green}%B%~%b%f Ꝥ '

# End of lines added by compinstall
